### ISSUE TITLE
NoMethodError: undefined method `class_attribute' for SugarCRM::Base:Class

### ISSUE THREAD

**Issue by anandamd** [chicks/sugarcrm#1]
Steps followed:
1. sudo gem install sugarcrm (Installed fine)
2. made sure activesupport (2.3.3) and json (1.4.6) gems are installed.
3. sudo ruby script/console 
   > require 'sugarcrm'  (produces the following error)

NoMethodError: undefined method `class_attribute' for SugarCRM::Base:Class
        from /usr/local/lib/ruby/gems/1.8/gems/sugarcrm-0.6.1/lib/sugarcrm.rb:25

Rails version is 2.3.3

**Comment by chicks** [comment]
Thanks for the bug!  I'm looking into this now.

**Comment by chicks** [comment]
I've fixed this bug, but I've found a few others.  0.6.2 will load, but if get_entry returns null then it will throw an exception.  I'm working on them as we speak.  Feel free to try out 0.6.2.

**Comment by anandamd** [comment]
Cool, Thanks Carl for a speedy fix :)
