### ISSUE TITLE
.all methods on Modules Return Record Instead of Array

### ISSUE THREAD

**Issue by frugardc** [chicks/sugarcrm#10]
Not sure if this is intended, but the .all method on a Module (SugarCRM::Opportunity, for example) returns a single record when the query returns a single record, rather than an array with one record.  I think all methods should always return arrays, even when they are empty.  Using version 0.9.4

**Comment by chicks** [comment]
You are 100% correct - let me put a fix in...

**Comment by chicks** [comment]
Pushed 0.9.5, and added unit tests to confirm functionality.

**Comment by frugardc** [comment]
When an empty resultset should be returned, (an empty array), the array returned contains one element, [false]

SugarOpportunity.all({:conditions => {:synced_c => "falsfe"}})
=> [false]

**Comment by frugardc** [comment]
will create a new issue...

**Comment by chicks** [comment]
Hah!  That's what happens when I make code changes at midnight - check out 0.9.6.
