### ISSUE TITLE
Fetch data from field of type 'Relate'

### ISSUE THREAD

**Issue by sudeepsnairontash** [chicks/sugarcrm#102]
I have a field named 'Consultant' which is of type 'Relate in a module named 'Appeals''. It is used to select a User's name from the User module. When I use Sugarcrm gem to fetch all details of 'Appeals' module the field 'Consultant' which is of type Relate and related to User module is showing 'nil' value. But I can see the value in SugarCRM.
Can any body help me?
thanks

**Comment by chicks** [comment]
Relate fields work differently via the Sugar API.  See this: http://criticallog.thornet.net/2013/07/25/sugarcrm-relate-field-vs-1-2-many-relationship/

**Comment by sudeepsnairontash** [comment]
Thank you chicks
