### ISSUE TITLE
Can not access Accounts module using sugarcrm ruby gem after upgrading to version 7.2.2 .

### ISSUE THREAD

**Issue by sudeepsnairontash** [chicks/sugarcrm#106]
Hi,
I have recently upgraded my SugarCRM professional version 6.7.7 to version 7.2.2. Since then, when I try to access my Accounts module using sugarcrm rub gem version 0.9.18, it shows error as:
"undefined method `klass' for false:FalseClass (NoMethodError)". None of the other modules show thisproblem. Please help me.
Thanks in advance
Sudeep...

**Comment by chicks** [comment]
I'll take a look this week, but my guess is there's an issue with the metadata in Sugar 7.2.2

**Comment by sudeepsnairontash** [comment]
hi Chicks,
Thank you for your response. Please do look in to this matter as soon as
you can, I am in trouble with this issue.
thanks,
Sudeep

**Comment by Steffylicious** [comment]
Any news on this?

**Comment by sudeepsnairontash** [comment]
No news yet. I am still stuck on this issue :(

**Comment by sudeepsnairontash** [comment]
Solved the issue by editing the file: lib\ruby\gems\2.0.0\gems\sugarcrm-0.9.18\lib\sugarcrm\association\association.rb.
Added code to the association.rb file

if module_name.to_s=="false"
else
return namespace.const_get(module_name.klass) if namespace.const_defined? module_name.klass
end

and commented out the line:
#return namespace.const_get(module_name.klass) if namespace.const_defined? module_name.klass

**Comment by bstephenf** [comment]
I apologize for a simple question, but where can I locate lib\ruby\gems\2.0.0\gems\sugarcrm-0.9.18\lib\sugarcrm\association\association.rb on Mac OSX?

**Comment by chicks** [comment]
try "gem env" from the terminal.

**Comment by bstephenf** [comment]
Thanks, I found it. So if I make this change as suggested - is there a compile command I would run or is that not necessary. Also, did you already accept this change into a version of the gem that I could just do an 'update' command to get? Thanks again.
