### ISSUE TITLE
Feature Request : User Password Management

### ISSUE THREAD

**Issue by frugardc** [chicks/sugarcrm#14]
Any way to trigger password resets emails to users or send them on user creation?  If I shouldn't be adding requests here, apologies.

Thanks

**Comment by chicks** [comment]
You can do this inside of SugarCRM with a Workflow, or Logic Hook.  It might already email the user on password reset - have you tried?

**Comment by davidsulc** [comment]
When writing a logic hook, I found this blog post really helpful http://redinkdesign.net/open-source/creating-logic-hooks-for-sugarcrm-5/

**Comment by frugardc** [comment]
Excellent.  Thanks.  Anything I can do to help this project?

**Comment by davidsulc** [comment]
(I speak for myself, I'm sure chicks will chime in himself.)

Report bugs and propose features :-)

SugarCRM prodives a lot of functions and we can't try all combinations of them to find all the cases where bugs arise in the gem.

In addition, I've only found features to add to chicks' gem when I was using it and thought "I really would need this feature right now"...

**Comment by chicks** [comment]
I second David's suggestions! :)

**Comment by frugardc** [comment]
Will do.  Thanks again for your excellent work!
