### ISSUE TITLE
Calling get_relationships on "modified_user_link" causes an HTTP 500 error.

### ISSUE THREAD

**Issue by chicks** [chicks/sugarcrm#16]
This is most likely a SugarCRM bug, but wanted to document it here.

**Steps to reproduce:**

```
SugarCRM.connection.get_relationships(
  "Accounts", SugarCRM::Account.first.id, "modified_user_link")
```

**Comment by davidsulc** [comment]
Seems to be a bigger issue relating to `_link` fields. The following doesn't work either:

`SugarCRM.connection.get_relationships("Accounts", SugarCRM::Account.first.id, "created_by_link")`

**Comment by chicks** [comment]
This _might_ be related to something we're doing, but I'm not sure.

The generated JSON is adding an id field to the related_fields key because it can't resolve the module name for modified_user_link.  

I might just update the code to add special handling for these fields, since modified_user and created_user will be present on almost every record.

**Comment by chicks** [comment]
ahhhh I figured this out - this was related to a bug on our end.  I'll commit a fix tonight.

**Comment by chicks** [comment]
Added fix and unit test.
