### ISSUE TITLE
Errno::ECONNRESET: Connection reset by peer

### ISSUE THREAD

**Issue by anandamd** [chicks/sugarcrm#2]
require 'sugarcrm'
=> true

s = SugarCRM::Base.establish_connection("http://sugarcrm",'admin','password',{:debug => false})
=> #<SugarCRM::Connection:0xa9f7e8c @pass="password", @user="admin", @session="1anv8casnovv0d7h8plh1m33q3", @ssl=false.............

SugarCRM::User.find(id)
(irb):5: warning: Object#id will be deprecated; use Object#object_id
Errno::EPIPE: Broken pipe

s.get_entry_list("Users","users.user_name = \'admin\'")
Errno::EPIPE: Broken pipe

s.connected?
=> true

s.logged_in?
=> true

s.get_entry_list("Users","users.user_name = \'admin\'")
Errno::EPIPE: Broken pipe

**Comment by chicks** [comment]
Oooooh, interesting.  I'm taking a look now.

**Comment by chicks** [comment]
By the way, thanks for all your testing and patience!  I didn't really expect anyone to use this gem yet, guess I shouldn't have put it in the public domain!  :)

**Comment by chicks** [comment]
What version of Sugar are you running?

**Comment by anandamd** [comment]
I am running community version 6.0

I am glad I am helping in some way :)

**Comment by anandamd** [comment]
hmm....works on my production box, but gives (above  mentioned) errors on my development box. So its not your code. Please accept my humble apologies!! :(

**Comment by chicks** [comment]
Eh, no worries.  Let me know if you figure out what it is!

**Comment by anandamd** [comment]
I am still digging into why my development box gives errors. However I have stumbled upon this onto my production box 

> > s.get_user_id

JSON::ParserError: source '"9f0d9fb5-74f1-a200-' not in JSON!
