### ISSUE TITLE
Stupid Question

### ISSUE THREAD

**Issue by frugardc** [chicks/sugarcrm#24]
What would the best practice for adding methods to a module be.  Like if I wanted to add methods to SugarCRM::Opportunities.  Normally in AR, I would just subclass it, but the queries return SugarCRM::Opportunities, which wouldn't have my methods.

**Comment by davidsulc** [comment]
The best way is to monkey patch it:

In a file, put something like

```
SugarCRM::Opportunity.class_eval do
  def self.find_big_ones(amt)
    self.all(:conditions => {:amount => "> #{amt}")
  end

  def is_big_one?
    self.amount > 1000
  end
end
```

This will give you a static method `SugarCRM::Opportunity.find_big_ones` you can call, as well as an instance method called with `opportunity.is_big_one?`. Not the most intelligent example, but it should get the point across...

Then, require this file AFTER connecting to SugarCRM with the gem. Class definitions are created during the connection, so it won't work if you require your monkey patch before the connection.

Let me know if you need any more help with this...

**Comment by chicks** [comment]
Also, at some point I'd like to add support for loading these types of extensions.  Not sure how to do it yet, but I've thought about this too...

**Comment by davidsulc** [comment]
I'm having trouble seeing what the advantage would be, could you explain?

Assuming we had a mechanism to monkey patch the gem, you'd still need to store and load the method definitions, so you're still basically stuck with loading a file. Unless you mean having a folder where monkey patches could be stored and loaded when the gem loads (similar to what Rails 3 does with the `initialize` folder)?

That last one could be quite interesting, assuming of course you always want to patch the same classes the same way (which is probably the use case for 99% of users). Let me know if that's what you mean, and I'll start looking into it: it's something I'm going to use quite often...

**Comment by chicks** [comment]
For me, the simple advantage would be the ability to add things like calculated fields, custom finders, etc. on top of the data returned from Sugar.  

Some common examples I run across rather frequently:
1. Calculating how long a case has been open and if it's crossed some kind of SLA threshold
2. Determining if it's a Contact's birthday
3. Determining the number of days it's been since there has been activity on an Account.

I was also thinking that people might want to build simple rails/sinatra/whatever apps on top of the gem (i.e. a customer portal) and it would be cool if the gem behaved similar to active record.  Specifically you could subclass SugarCRM::Contact and define methods that would get picked up whenever the module registration code ran.

I don't think it would be very hard to do, and a number of options come to mind:
1. Pass an option to SugarCRM.connect
2. Patch Module.register to check for an existing constant, and call class_eval instead of const_define 
3. Make the gem look for customizations in certain locations on the filesystem.

I'm open to any implementation, and am curious what you guys think.

**Comment by davidsulc** [comment]
Yeah, I absolutely see the need for monkey patching (I use it myself for environment specific methods). I didn't see the need for "automagical" monkey patching.

See https://github.com/davidsulc/sugarcrm/commit/774e16b38f33fefc5afe1c453eb9e53ac6704d22 for a first pass on the idea. Here's my reasoning behind this implementation:
- the Environment class can later be reused to store/fetch various environment info (e.g. Sugar version)
- Apps/users can either dump their customizations into the folder that is automatically loaded by the gem (lib/sugarcrm/monkey_patches), or they can call `SugarCRM::Environment.monkey_patch_folder =` to load their monkey patches present in a custom folder (e.g. when you don't have access to the gem folder).

Any feedback? Also, let me know if I should push this to chicks/sugarcrm.

**Comment by chicks** [comment]
Looks good to me!  Can we write some tests for it?

**Comment by frugardc** [comment]
Would any of these methods allow you to make changes in a Rails app, and reload! to get the changes without having to restart the rails console?

**Comment by davidsulc** [comment]
Yes, if you call `SugarCRM::Environment.monkey_patch_folder =` again it will reload all the patches you have in that folder. Note that if you call `reload!` in the Rails console, it won't automatically reload the monkey patches. You'll need to call the method above.

Tests have been added. Pushed to chicks/sugarcrm.

**Comment by chicks** [comment]
We could also add a method like SugarCRM::Environment.reload!

I might look into how rails does it - perhaps we could hook into their lifecycle somehow.

**Comment by davidsulc** [comment]
We could definitely add a `reload!` method. If we do, we'll have to think about how an end user would use that method, to make sure it satisfies the use cases for it and doesn't confuse the user.

For example, if a user create a new link between 2 modules in the Studio and calls `reload!`, he might expect the relationship to now be available. (Which would be the case in Rails' console.)

**Comment by chicks** [comment]
Yeah - we can always just call Module.register_all (or reconnect) to pull module changes. (we might need to unregister_all before this, or something)

Also, a lot of gems detect if rails is present in the environment and then do stuff to hook into functions like these.

**Comment by frugardc** [comment]
Adding to the Rails reload! would be great.  The monkey_patch folder could work as well.  Let me know if you post those changes and I will play around with it.

As far as the re-registering to pull module changes, I can say that when I was using the gem at first, I was thinking that might be the case.

**Comment by davidsulc** [comment]
The changes have been pushed to chicks' repository, so go ahead and give them a spin.

There's a brief explanation on monkey patching in the gem's readme, if necessary.

Let us know if things go wrong...

**Comment by frugardc** [comment]
Confirming the monkey_patch folder method works... Thanks!

**Comment by davidsulc** [comment]
No problem ;-)
