### ISSUE TITLE
Custom Fields in Query

### ISSUE THREAD

**Issue by tsuzanski** [chicks/sugarcrm#25]
Hello, 

I am also having problems with queries with custom fields.  I saw an issue on this that was closed a few weeks ago and am not sure if this is the same.  

I have version 0.9.8 of sugarcrm
I have a custom field called: account_number_c

I am doing:

SugarCRM::Account.all({:conditions => {:account_number_c => "10000000"}})

And get
undefined method `account_number_c' for "Database failure. Please refer to sugarcrm.log for details.":String (NoMethodError)

In the log I see:

[FATAL] Error running count query for Account List:  Query Failed:  SELECT count(*) c FROM accou\
nts   LEFT JOIN accounts_cstm ON accounts.id = accounts_cstm.id_c   LEFT JOIN  users jt0 ON
jt0.id= accounts.modified_user_id AND jt0.deleted=0
 AND jt0.deleted=0  LEFT JOIN  users jt1 ON
jt1.id= accounts.created_by AND jt1.deleted=0
 AND jt1.deleted=0  LEFT JOIN  users jt2 ON
jt2.id= accounts.assigned_user_id AND jt2.deleted=0
 AND jt2.deleted=0  LEFT JOIN  accounts jt3 ON
jt3.id= accounts.parent_id AND jt3.deleted=0
 AND jt3.deleted=0  LEFT JOIN  campaigns jt4 ON
jt4.id= accounts.campaign_id AND jt4.deleted=0
 AND jt4.deleted=0  LEFT JOIN  users jt5 ON
jt5.id= accounts.modified_user_id AND jt5.deleted=0
 AND jt5.deleted=0 where (.account_number_c = '10000000') AND accounts.deleted=0: MySQL error 1064: You have an error in your SQL syntax; check the manual that corres\
ponds to your MySQL server version for the right syntax to use near '= '10000000') AND accounts.deleted=0' at line 13

Any help would be much appreciated.  The gem is awesome. 

Thanks!

**Comment by davidsulc** [comment]
I believe this issue is fixed in the HEAD version (commit https://github.com/chicks/sugarcrm/commit/b6e33f5ea08d41b45fe93dc2a38e108b9ea2be3d). Can you update, and try again?

Instructions on how to use HEAD here : https://github.com/chicks/sugarcrm/issues/closed#issue/19/comment/697464

Note: the location where you should copy the gem files will depend on your system (Windows VS Linux, etc.). Try searching for the `sugarcrm-0.9.8` folder to see where the gem is stored on your system.

**Comment by chicks** [comment]
Thanks for the bug!

We need to determine if this is a bug in your sugar installation or an issue with the way we handle custom fields in the gem.  The actual error pertains to the SQL - specifically the line:

```
 AND jt5.deleted=0 where ( .account_number_c = '10000000') AND accounts.deleted=0: 
```

_.account_number_c_ is not a valid SQL table and column name.  

Can you send me the output of:

```
SugarCRM.connection.debug = true
SugarCRM::Account.all({:conditions => {:account_number_c => "10000000"}})
```

**Comment by chicks** [comment]
Also, if it's fixed in HEAD - I will be cutting a new gem tonight with all of the changes that have been submitted over the past two weeks.

**Comment by davidsulc** [comment]
Chicks, I think this is fixed with https://github.com/chicks/sugarcrm/commit/b6e33f5ea08d41b45fe93dc2a38e108b9ea2be3d I ran into the same issue.

**Comment by chicks** [comment]
Ahhhhh, nice.

**Comment by davidsulc** [comment]
I took the opportunity to de-uglify that just now...

**Comment by tsuzanski** [comment]
Thanks everyone. I tried the latest fix in module.rb and it seems to work.  Nice job.
