### ISSUE TITLE
Won't Add Custom Objects to Custom Relationships

### ISSUE THREAD

**Issue by frugardc** [chicks/sugarcrm#27]
Adding a Custom Module "Sid1ContactType" to an Opportunity.  Everything seems to go OK, until the save of the opportunity, which returns false.  Inspecting errors on the opportunity returns an empty set.  Verified that this type of join works through the frontend.

irb(main):004:0> ct = SugarCRM::Sid1ContactType.new

=> #<SugarCRM::Sid1ContactType assigned_user_id: nil, assigned_user_name: nil, created_by: nil, created_by_name: nil, date_entered: nil, date_modified: nil, deleted: false, description: nil, id: nil, modified_by_name: nil, modified_user_id: nil, name: nil, opportunities_sid1_contact_types_name: nil, sid1_contact_types_contacts_name: nil, sid1_contact_types_opportunities_name: nil, team_count: nil, team_id: nil, team_name: nil, team_set_id: nil, types_c: nil>

irb(main):005:0> ct.required_attributes

=> [:types_c]

irb(main):006:0> ct.types_c = "a_loc"

=> "a_loc"

irb(main):008:0> ct.save

=> true

irb(main):009:0> o = SugarCRM::Opportunity.first
=> #<SugarCRM::Opportunity account_id: nil, account_name: "Slender Broadband Inc", amount: "75000", amount_usdollar: "75000", assigned_user_id: "seed_chris_id", assigned_user_name: "Chris Olliver", campaign_id: "", campaign_name: nil, created_by: "1", created_by_name: "Sidera Administrator", currency_id: "-99", currency_name: "", currency_symbol: "", date_closed: "2011-11-06", date_entered: "2011-01-25 18:20:54", date_modified: "2011-01-29 21:39:18", deleted: false, description: "", id: "1a7a1422-c5b1-2e13-0d0e-4d3f142d850b", lead_source: "Other", modified_by_name: "Sidera Administrator", modified_user_id: "1", name: "Slender Broadband Inc - 1000 units", next_step: "", opportunity_type: "", probability: 70, sales_stage: "Perception Analysis", sid1_contact_types_opportunities_name: "", team_count: "3", team_id: "East", team_name: "East ", team_set_id: "539b4447-b5c3-c71e-78bc-4d3f142190fa">

irb(main):011:0> o.valid?

=> true

irb(main):012:0> o.sid1_contact_types

=> #<SugarCRM::AssociationCollection:0x7fb5c62fa5e8 @collection=[], @owner=#<SugarCRM::Opportunity account_id: nil, account_name: "Slender Broadband Inc", amount: "75000", amount_usdollar: "75000", assigned_user_id: "seed_chris_id", assigned_user_name: "Chris Olliver", campaign_id: "", campaign_name: nil, created_by: "1", created_by_name: "Sidera Administrator", currency_id: "-99", currency_name: "", currency_symbol: "", date_closed: "2011-11-06", date_entered: "2011-01-25 18:20:54", date_modified: "2011-01-29 21:39:18", deleted: false, description: "", id: "1a7a1422-c5b1-2e13-0d0e-4d3f142d850b", lead_source: "Other", modified_by_name: "Sidera Administrator", modified_user_id: "1", name: "Slender Broadband Inc - 1000 units", next_step: "", opportunity_type: "", probability: 70, sales_stage: "Perception Analysis", sid1_contact_types_opportunities_name: "", team_count: "3", team_id: "East", team_name: "East ", team_set_id: "539b4447-b5c3-c71e-78bc-4d3f142190fa">, @association=:sid1_contact_types_opportunities, @original=[], @loaded=true>

irb(main):013:0> o.sid1_contact_types << ct

=> #<SugarCRM::AssociationCollection:0x7fb5c62fa5e8 @collection=[#<SugarCRM::Sid1ContactType assigned_user_id: nil, assigned_user_name: nil, created_by: nil, created_by_name: nil, date_entered: nil, date_modified: nil, deleted: false, description: nil, id: "b99eaab1-4bc6-9ed2-52a2-4d4489f4891e", modified_by_name: nil, modified_user_id: nil, name: nil, opportunities_sid1_contact_types_name: nil, sid1_contact_types_contacts_name: nil, sid1_contact_types_opportunities_name: nil, team_count: nil, team_id: nil, team_name: nil, team_set_id: nil, types_c: "a_loc">], @owner=#<SugarCRM::Opportunity account_id: nil, account_name: "Slender Broadband Inc", amount: "75000", amount_usdollar: "75000", assigned_user_id: "seed_chris_id", assigned_user_name: "Chris Olliver", campaign_id: "", campaign_name: nil, created_by: "1", created_by_name: "Sidera Administrator", currency_id: "-99", currency_name: "", currency_symbol: "", date_closed: "2011-11-06", date_entered: "2011-01-25 18:20:54", date_modified: "2011-01-29 21:39:18", deleted: false, description: "", id: "1a7a1422-c5b1-2e13-0d0e-4d3f142d850b", lead_source: "Other", modified_by_name: "Sidera Administrator", modified_user_id: "1", name: "Slender Broadband Inc - 1000 units", next_step: "", opportunity_type: "", probability: 70, sales_stage: "Perception Analysis", sid1_contact_types_opportunities_name: "", team_count: "3", team_id: "East", team_name: "East ", team_set_id: "539b4447-b5c3-c71e-78bc-4d3f142190fa">, @association=:sid1_contact_types_opportunities, @original=[], @loaded=true>
irb(main):014:0> o.save
=> false

irb(main):016:0> o.errors
=> #<Set: {}>

**Comment by davidsulc** [comment]
What happens if you try `o.associate!(ct)` ?

**Comment by frugardc** [comment]
irb(main):003:0> o.associate!(ct)

SugarCRM::AssociationFailed: Couldn't associate Opportunities: 1a7a1422-c5b1-2e13-0d0e-4d3f142d850b -> #<SugarCRM::Sid1ContactType assigned_user_id: "", assigned_user_name: " ", created_by: "1", created_by_name: "Sidera Administrator", date_entered: "2011-01-25 18:50:09", date_modified: "2011-01-25 18:50:09", deleted: false, description: "", id: "1e2c6e67-e8c8-281e-bfbd-4d3f1b21cda2", modified_by_name: "Sidera Administrator", modified_user_id: "1", name: "", opportunities_sid1_contact_types_name: "                                                   ...", sid1_contact_types_contacts_name: "                                                   ...", sid1_contact_types_opportunities_name: "", team_count: "1", team_id: "1", team_name: "Global ", team_set_id: "1", types_c: "^a_loc^,^z_loc^">: 1e2c6e67-e8c8-281e-bfbd-4d3f1b21cda2!
    from /usr/lib/ruby/gems/1.8/gems/sugarcrm-0.9.8/lib/sugarcrm/associations/association_methods.rb:37:in `associate!'
    from /usr/lib/ruby/gems/1.8/gems/sugarcrm-0.9.8/lib/sugarcrm/associations/association_methods.rb:30:in`each'
    from /usr/lib/ruby/gems/1.8/gems/sugarcrm-0.9.8/lib/sugarcrm/associations/association_methods.rb:30:in `associate!'
    from (irb):3

irb(main):004:0> o.associations

=> [, sid1_contact_types_opportunities, , , , , , campaign_opportunities, , , , opportunities_sid1_contact_types, , , , , , , , , , , , , , , ]
irb(main):005:0>

**Comment by frugardc** [comment]
and for good measure...

irb(main):005:0> ct.associate!(o)

SugarCRM::AssociationFailed: Couldn't associate sid1_contact_types: 1e2c6e67-e8c8-281e-bfbd-4d3f1b21cda2 -> #<SugarCRM::Opportunity account_id: nil, account_name: "Slender Broadband Inc", amount: "75000", amount_usdollar: "75000", assigned_user_id: "seed_chris_id", assigned_user_name: "Chris Olliver", campaign_id: "", campaign_name: nil, created_by: "1", created_by_name: "Sidera Administrator", currency_id: "-99", currency_name: "", currency_symbol: "", date_closed: "2011-11-06", date_entered: "2011-01-25 18:20:54", date_modified: "2011-01-29 21:43:18", deleted: false, description: "", id: "1a7a1422-c5b1-2e13-0d0e-4d3f142d850b", lead_source: "Other", modified_by_name: "Sidera Administrator", modified_user_id: "1", name: "Slender Broadband Inc - 1000 units", next_step: "", opportunity_type: "", probability: 70, sales_stage: "Perception Analysis", sid1_contact_types_opportunities_name: "", team_count: "3", team_id: "East", team_name: "East ", team_set_id: "539b4447-b5c3-c71e-78bc-4d3f142190fa">: 1a7a1422-c5b1-2e13-0d0e-4d3f142d850b!
    from /usr/lib/ruby/gems/1.8/gems/sugarcrm-0.9.8/lib/sugarcrm/associations/association_methods.rb:37:in `associate!'
    from /usr/lib/ruby/gems/1.8/gems/sugarcrm-0.9.8/lib/sugarcrm/associations/association_methods.rb:30:in`each'
    from /usr/lib/ruby/gems/1.8/gems/sugarcrm-0.9.8/lib/sugarcrm/associations/association_methods.rb:30:in `associate!'
    from (irb):5
irb(main):006:0>

**Comment by davidsulc** [comment]
Hopefully, this will shed some light on the issue: what's the output of

```
SugarCRM::Sid1ContactType._module.name
SugarCRM::Sid1ContactType._module.table_name
SugarCRM::Sid1ContactType._module.custom_table_name
```

**Comment by davidsulc** [comment]
Could also provide data on a correct join, with all attributes of the `Opportunity`, `Contact`, and `ContactType`?

I have a feeling we might be able to apply a non-intrusive temporary fix (with a `rescue`) while finding a better way... But we'll need tof igure out how to make it work properly, and according to https://github.com/chicks/sugarcrm/issues#issue/23 the only information on the link is the `name` (no `id`), which I ifnd hard to believe.

Could you also maybe provide the Sugar log corresponding to creating a new `ContactType`, and then
- clicking on the link to the `Opportunity` from within the `ContactType`
- clicking on the link to the `Contact` from within the `ContactType`
- clicking on the link to the `ContactType` from the `Opportunity`
- clicking on the link to the `ContactType` from the `Contact`

That might help us see how Sugar links those modules...

**Comment by frugardc** [comment]
OK.  Part 1:

irb(main):022:0> SugarCRM::Sid1ContactType._module.name

=> "sid1_contact_types"

irb(main):023:0> SugarCRM::Sid1ContactType._module.table_name

=> "sid1_contact_types"

irb(main):024:0> SugarCRM::Sid1ContactType._module.custom_table_name

=> "sid1_contact_types_cstm"

**Comment by frugardc** [comment]
Although this works in the SugarApplication, I am seeing errors relating to finding the relationship.  I have a feeling there is an issue with the application clearing out deleted relationships (I created this relationship once, deleted, then recreated it ).  Might be possible that the module still thinks there is more than one relationship, and that is confusing the application\REST Module\ Gem.  Will update the case.

**Comment by frugardc** [comment]
Question:  is associate! the preferred way to create an association between two objects?

**Comment by chicks** [comment]
Yes, assuming the association can be inferred from the module_fields.  

It's the primary method that the rest of the gem uses.  If you can't get it to work (because of inconsistent metadata), you can always use the set_relationship API call.

**Comment by davidsulc** [comment]
Also, FYI, `associate!` doesn't load existing associations before creating a new one. (It's essentially a wrapper for set_relationship.)

In other words, if `account` has a lot of contacts and you want to add one, `account.associate!(contact)` will be much quicker than `account.contacts << contact`, because the related contacts won't be fetched from Sugar first.

**Comment by frugardc** [comment]
Closing.  I have this working I think.  I think there are some nuances to the order in which finding or creating an object, then associating it, and the like are not completely ironed out, but since I can procede at this point, I should probably close and then re-open when I have a better handle on the issue.  Thanks again for the help!

**Comment by chicks** [comment]
Okay!  Let me know if we need to make the documentation clearer, or if a particular use case isn't working.
