### ISSUE TITLE
SugarCRM::Account.new.associations returns an array with nil values

### ISSUE THREAD

**Issue by chicks** [chicks/sugarcrm#29]
From head:

SugarCRM::Account.new.associations
 => [, , , , , , , , , , , , , , , , , , , , , , , , , ]

**Comment by davidsulc** [comment]
It seems `Associations#to_s` isn't correct. I can't quite understand why the code is that way. Maybe we should store relationship names when calling `Association#humanized_link_name`?

(This is a bigger issue: `SugarCRM::Contact.first.associations` won't list accounts as a relationship, for example.)

**Comment by chicks** [comment]
From what I can tell, this was a cosmetic issue.  I've pushed some fixes to HEAD
