### ISSUE TITLE
Unable to pass ampersand in a string on save!

### ISSUE THREAD

**Issue by rsennewald** [chicks/sugarcrm#32]
I don't believe some special characters are being escaped when attempting to do a set entry from the save! method.  I've found this to be the case when putting an ampersand (&) in a string.  In my situation I was creating a new user with the department as 'G&A' and the server won't accept it, I get a SugarCRM::InvalidRequest with all the json saying it is invalid.

**Comment by davidsulc** [comment]
Are you using the latest version? This should have been fixed with https://github.com/chicks/sugarcrm/commit/d9c66c87345eec855635e230040eaba146f512c1

**Comment by rsennewald** [comment]
I apologize for not being on the newest version of the gem, as I see this was fixed after I had upgraded.

**Comment by chicks** [comment]
The irony is that Ray sits right next to me.

**Comment by davidsulc** [comment]
No problem. Try to sneak your tests onto Charles' computer ;-)
