### ISSUE TITLE
Error with SugarCRM::User module 'undefined method `session' '

### ISSUE THREAD

**Issue by frugardc** [chicks/sugarcrm#37]
irb(main):027:0> SugarCRM::User.first
NoMethodError: undefined method `session' for #<Class:0x7fa608e49700>
    from /usr/lib/ruby/gems/1.8/gems/activerecord-3.0.3/lib/active_record/base.rb:1008:in`method_missing'
    from /usr/lib/ruby/gems/1.8/gems/sugarcrm-0.9.11/lib/sugarcrm/base.rb:52:in `connection'
    from /usr/lib/ruby/gems/1.8/gems/sugarcrm-0.9.11/lib/sugarcrm/finders/finder_methods.rb:89:in`find_by_sql'
    from /usr/lib/ruby/gems/1.8/gems/sugarcrm-0.9.11/lib/sugarcrm/finders/finder_methods.rb:6:in `find_initial'
    from /usr/lib/ruby/gems/1.8/gems/sugarcrm-0.9.11/lib/sugarcrm/base.rb:35:in`find'
    from /usr/lib/ruby/gems/1.8/gems/sugarcrm-0.9.11/lib/sugarcrm/base.rb:58:in `first'
    from (irb):27

**Comment by davidsulc** [comment]
Can't reproduce. Can you post all the code you executed?

**Comment by frugardc** [comment]
That was pretty much it.  SugarCRM::User.first bombs out.  It only seems to do it in version 0.9.11 .  I reverted to 0.9.10 and the issue goes away.

**Comment by davidsulc** [comment]
Yeah, 0.9.11 was a pretty big change: it allows simultaneous connections to several CRM servers, so a lot of stuff was changed.

Can you try executing the following in `irb`:

```
require 'sugarcrm'
SugarCRM.connect(...)
SugarCRM.used_namespaces
SugarCRM.namespaces
SugarCRM::User.first
```

And tell me the output? Are you using a config file?

**Comment by chicks** [comment]
Why are we hitting method_missing on ActiveRecord::Base?  Are you using this inside of Rails?

**Comment by davidsulc** [comment]
For what it's worth, `SugarCRM::User.first` works fine with v 0.9.11 in a trivial rails app too (such as https://github.com/davidsulc/sugar_on_rails_basic).

**Comment by davidsulc** [comment]
Is this still an issue?

**Comment by frugardc** [comment]
Does't appear to be an issue any longer.  Sorry for the delay, was pulled off on another project for a few days.  Closing.

**Comment by alindeman** [comment]
If you have a `User` model and were using Ruby >= 1.9, this might have been the cause: https://github.com/chicks/sugarcrm/pull/69
