### ISSUE TITLE
Link field pollution

### ISSUE THREAD

**Issue by davidsulc** [chicks/sugarcrm#43]
Documented with SugarCRM as bug 43340

If a user creates a relationship and then deletes it, the vardefs.ext.php (e.g. for Contacts module: custom/modules/Contacts/Ext/Vardefs/vardefs.ext.php) aren't updated properly: the link is still present in the vardefs file, even if the join tables are deleted.

This link_field (for an inexistent relationship) is returned when the REST API for get_module_fields is called, which pollutes the link_field namespace and can make it impossible to access the desired relationship programmatically (e.g. REST API wrapper).

Steps to reproduce:
1. Call get_module_fields("Contacts") and look at the list of fields: there is no "contacts_opportunities" field
2. Create a one-to-many relationship in Studio between Contacts and Opportunities and deploy it
3. Delete the relationship in Studio (including tables)
4. Call get_module_fields("Contacts") and notice there is now a "contacts_opportunities" field although this second relationship between these 2 modules doesn't exist (it was deleted in step 3)

Proposed solution: when deleting a relationship in Studio, make sure the vardefs for the modules get updated correctly.

**Comment by chicks** [comment]
I'm going to update this bug and see about escalating it.  Should be a simple fix.

**Comment by davidsulc** [comment]
FYI

Ran Zhou has updated a bug:

Bug Number: 43340
Subject: Deleted relationships returned with get_module_fields (REST API)
Priority: Medium
Status: Assigned
Type: Defect
*Fixed in Release: _6.4.0.patch
