### ISSUE TITLE
Invalid Sessions

### ISSUE THREAD

**Issue by frugardc** [chicks/sugarcrm#49]
I am running a Rails application service that will handle requests to update data in SugarCRM.  How can I test to make sure that the SugarCRM session is valid, and if it is not, reconnect?

Thanks!

**Comment by chicks** [comment]
The gem should do this for you.  Is it not?

**Comment by frugardc** [comment]
From time to time, I get an "Invalid session" error and have to kill the
server or console to get it back.

**Comment by davidsulc** [comment]
Hmm. I've never run into this problem (full disclosure, I've never built a complete portal either).

Is it possible the issue is related to the Rails app not being able to get a connection (to SugarCRM) from the pool before the specified timeout ? Can you post a stack trace ?

**Comment by chicks** [comment]
Stack trace would be awesome.  Also, any input you have on how to recreate the condition would be good.

**Comment by chicks** [comment]
Just checking in!

**Comment by chicks** [comment]
Christian, just checking in.  Is this still a problem?

**Comment by chicks** [comment]
Christian, I added better handling of invalid sessions in 0.9.16.  Let me know if this helps!
