### ISSUE TITLE
invalid session with set_note_attachment

### ISSUE THREAD

**Issue by openhealth** [chicks/sugarcrm#50]
Hi all, when using set_note_attachment, I get an invalid session error coming from the sugarcrm side. Here is my example code:

SugarCRM.connect(Cust::SUGAR_URL, Cust::SUGAR_USERNAME, Cust::SUGAR_PASSWORD)
...
File.open(path, 'w') {|f| f.write(data_bytes) }
file = File.read("/tmp/hello.pdf")
n = SugarCRM::Note.new
n.name = "blah"
n.team_name = 'global'
n.team_count = 1
n.save
# n.id is true and valid.

SugarCRM.connection.set_note_attachment(n.id, "hello.pdf", file)

At this point, an error occurs in the sugarcrm log:
[4517][-none-][ERROR] 11: Invalid Session ID<br>The session ID is invalid

I can't work out why it's doing it. The json that gets sent appears to be valid, and get_note_attachment works fine. I then created a standalone app without using the sugarcrm gem and called set_note_attachment directly and this worked fine, so as far as I can tell, it seems to be an issue with the sugarcrm gem. Testing on sugarcrm version 6.1.

Any ideas? Thank you for any help...

**Comment by chicks** [comment]
Can you enable debugging on the connection with:

```
SugarCRM.connect(Cust::SUGAR_URL, Cust::SUGAR_USERNAME, Cust::SUGAR_PASSWORD. {:debug => true})
```

and paste the output of the JSON request/response for set_note_attachment?

**Comment by openhealth** [comment]
Sure no probs, here it is:

set_note_attachment: Request:
{
  "session": "veruqtjviqq05pfq4m2j2jkh94",
     "note": {
        "id": "200e66a1-7a8c-02cb-2559-4dc0a9cc7db6",
        "filename": "hello.pdf",
        "file": "JVBERi0xLjMKJf////8KMSAwIG9iago8PCAvQ3JlYXRvciAoUHJhd24pCi9Q
cm9kdWNlciAoUHJhd24pCj4+CmVuZG9iagoyIDAgb2JqCjw8IC9Db3VudCAx
Ci9LaWRzIFs1IDAgUl0KL1R5cGUgL1BhZ2VzCj4+CmVuZG9iagozIDAgb2Jq
Cjw8IC9UeXBlIC9DYXRhbG9nCi9QYWdlcyAyIDAgUgo+PgplbmRvYmoKNCAw
IG9iago8PCAvTGVuZ3RoIDM1OQo+PgpzdHJlYW0KL0RldmljZVJHQiBjcwow
LjAwMCAwLjAwMCAwLjAwMCBzY24KL0RldmljZVJHQiBDUwowLjAwMCAwLjAw
MCAwLjAwMCBTQ04KcQoKQlQKMzYgNzQxLjY0IFRkCi9GMi4wIDIwIFRmCls8
NDM2ZjZlNzQ2MTYzNzQyMD4gNTAgPDU0PiAxMjAgPDc3PiAxMCA8NmY+XSBU
SgpFVAoKCkJUCjM2IDcxOC41MiBUZAovRjIuMCAyMCBUZgpbPD5dIFRKCkVU
CgoKQlQKMzYgNzAxLjE0NCBUZAovRjEuMCAxMiBUZgpbPDQ0NjU3MzYzNzI+
IC0xNSA8Njk3MDc0Njk2ZjZlMjAzND5dIFRKCkVUCgoKQlQKMzYgNjg3LjI3
MiBUZAovRjEuMCAxMiBUZgpbPDQ0NjU3MzYzNzI+IC0xNSA8Njk3MDc0Njk2
ZjZlMjAzNDYxNzM2NjczNjQ+XSBUSgpFVAoKUQoKZW5kc3RyZWFtCmVuZG9i
ago1IDAgb2JqCjw8IC9NZWRpYUJveCBbMCAwIDYxMi4wIDc5Mi4wXQovQ29u
dGVudHMgNCAwIFIKL1Jlc291cmNlcyA8PCAvUHJvY1NldCBbL1BERiAvVGV4
dCAvSW1hZ2VCIC9JbWFnZUMgL0ltYWdlSV0KL0ZvbnQgPDwgL0YxLjAgNyAw
IFIKL0YyLjAgNiAwIFIKPj4KPj4KL1BhcmVudCAyIDAgUgovVHlwZSAvUGFn
ZQo+PgplbmRvYmoKNiAwIG9iago8PCAvRW5jb2RpbmcgL1dpbkFuc2lFbmNv
ZGluZwovQmFzZUZvbnQgL0hlbHZldGljYS1PYmxpcXVlCi9TdWJ0eXBlIC9U
eXBlMQovVHlwZSAvRm9udAo+PgplbmRvYmoKNyAwIG9iago8PCAvRW5jb2Rp
bmcgL1dpbkFuc2lFbmNvZGluZwovQmFzZUZvbnQgL0hlbHZldGljYQovU3Vi
dHlwZSAvVHlwZTEKL1R5cGUgL0ZvbnQKPj4KZW5kb2JqCnhyZWYKMCA4CjAw
MDAwMDAwMDAgNjU1MzUgZiAKMDAwMDAwMDAxNSAwMDAwMCBuIAowMDAwMDAw
MDcxIDAwMDAwIG4gCjAwMDAwMDAxMjggMDAwMDAgbiAKMDAwMDAwMDE3NyAw
MDAwMCBuIAowMDAwMDAwNTg3IDAwMDAwIG4gCjAwMDAwMDA3NzcgMDAwMDAg
biAKMDAwMDAwMDg4MiAwMDAwMCBuIAp0cmFpbGVyCjw8IC9TaXplIDgKL1Jv
b3QgMyAwIFIKL0luZm8gMSAwIFIKPj4Kc3RhcnR4cmVmCjk3OQolJUVPRgo=
",
        "related_module_id": "",
        "related_module_name": "" 
     }
}

set_note_attachment: JSON Response:
{"number"=>11,
 "name"=>"Invalid Session ID",
 "description"=>"The session ID is invalid"}

**Comment by chicks** [comment]
Ahhh... there's a newline at the end of the base64 encoded file string.  I've fixed this in HEAD, but I need to cut another gem.  Let me patch up some of the tests and get this released.

**Comment by openhealth** [comment]
Ah no worries, thank you =)

**Comment by chicks** [comment]
Okay, give gem version 0.9.14 a spin and let me know if that fixes things.

**Comment by openhealth** [comment]
Ah excellent, this has fixed the issue! Thanks very much.

**Comment by chicks** [comment]
Suh-weet.
