### ISSUE TITLE
Need to correct extensions example SugarCRM::Contact.ten_oldest 

### ISSUE THREAD

**Issue by charlez** [chicks/sugarcrm#64]
The extensions example shown within lib/sugarcrm/extensions/README.txt  isn't fully correct.  If the example extension code is enabled and executed, invocation of method SugarCRM:Contact.ten_oldest yields:

ruby-1.9.2-p290 :005 > SugarCRM::Contact.ten_oldest
SugarCRM::RecordNotFound: Couldn't find Contacts without an ID
    from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/sugarcrm-0.9.16/lib/sugarcrm/finders/finder_methods.rb:19:in `find_from_ids'
    from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/sugarcrm-0.9.16/lib/sugarcrm/base.rb:58:in`find'
    from /usr/local/rvm/gems/ruby-1.9.2-p290/gems/sugarcrm-0.9.16/lib/sugarcrm/extensions/ExampleExtensions.rb:4:in `ten_oldest'
    from (irb):5
    from /usr/local/rvm/rubies/ruby-1.9.2-p290/bin/irb:16:in`<main>'

**Comment by chicks** [comment]
Updated!

**Comment by chicks** [comment]
Closing.
