### ISSUE TITLE
Can't associate Accounts with Quotes

### ISSUE THREAD

**Issue by gpedic** [chicks/sugarcrm#67]
When I try to create an association between an account and a quote using for example:

acc = SugarCRM::Account.find('any-account-id')
quot = SugarCRM::Quote.new({ 
:name => "test", 
:billing_account_name: acc.name
...
})
acc.quotes << quot

The assignment fails with:
SugarCRM::InvalidAssociation (Could not lookup association for: #<SugarCRM::Namespace0::Account ...

on line 72 in association_collection.rb:
record.update_association_cache_for(record.associations.find!(@owner).link_field, @owner, :add)

As far as I can tell the it's because SugarCRM::Quote has no association to SugarCRM::Account, 
quot.associations.find!(acc) -> returns false
but the opposite is true for Accounts
acc.associations.find!(quot) -> returns true

Adding the missing association seems like the most likely fix for this, but I'm not really sure how to do it.

**Comment by davidsulc** [comment]
Hi,

You are correct, you'll need to create a relationship between the two modules form the SugarCRM Studio. Only then will you be able to link module instances to one another.

You cannot create create the relationship between modules from the gem, you can only create associations between module instances. In other words, you have to use the SugarCRM Studio to make it possible to link a Quote to an Account (by creating a new relationship). However, if that relationship exists, you'll be able to create new associations using the gem.

To solve your problem, go in the admin panel and click on "Studio". From within the "Account" menu, select "relationships" and create a new relationship to the "Quote" module. Finaly, save and deploy. Then next time your gem connects, you should be able to link quotes to accounts.

Lets us know if you run into any issues.

**Comment by chicks** [comment]
Yeah, I think quotes are intended to hang off of opportunities.

Sooo... Account -> Opportunities -> Quote

This can be tweaked in Studio if needed.

**Comment by gpedic** [comment]
Thank you for your feedback.

What I was trying/hoping to do is to somehow automatically set shipping and billing details by associating the quote with a account (as billing account), but I realize now that i was a bit too ambitious and that gem associations don't work that way. 

About associating the two modules, I've tried adding a one-to-many relation Account -> Quotes and that took care of the error, but the gem doesn't  associate the two modules using the procedure from the example (it doesn't even set the Account relate field) . 
Also, the Account and Quote modules already have 2 many-to-many relationships and adding additional relationships just doesn't feel like the right way to go. 

The interesting thing for me is that the gem seems only to be able to see one relationship/association from Accounts to Quotes:
 SugarCRM::Namespace0::Association @proxy_methods=[quotes_shipto], @link_field="quotes_shipto", @target=SugarCRM::Namespace0::Quote, @owner=SugarCRM::Namespace0::Account, @cardinality=:many_to_one 

But there is an additional link_field named 'quotes' on the Account side and two called 'shipping_accounts' and 'billing_accounts' on the Quote side defined in the corresponding vardefs. The relation that associates Accounts and Quotes inside sugarcrm is 'quotes_billto_accounts'.  

I've worked around this "issue" by setting the billing and shipping info from the account manually and then just calling:
SugarCRM.connection.set_relationship("Quotes",@quote.id,"billing_accounts",[@account.id]) to relate the two.

**Comment by davidsulc** [comment]
If you want to have some data automatically set (e.g. when a new record is saved), you'll need to use SugarCRM's LogicHooks for that and program the functionality in PHP. There is no way for the gem to be triggered based on CRM actions. The closest you can get is to poll SugarCRM records and set the info then...

You're correct that there is no way for the gem to differentiate between multiple relationships between two CRM modules. That is an issue with the SugarCRM API, which we've documented with SugarCRM (https://github.com/chicks/sugarcrm/issues/44).
