### ISSUE TITLE
Invalid gemspec in git repo

### ISSUE THREAD

**Issue by davidsulc** [chicks/sugarcrm#71]
sugarcrm at /home/david/.rvm/gems/ruby-1.9.2-p0/bundler/gems/sugarcrm-c22b789b4699 did not have a valid gemspec.  
This prevents bundler from installing bins or native extensions, but that may not affect its functionality.  
The validation message from Rubygems was:
  ["./Gemfile.lock", "./sugarcrm.tmproj"] are not files

**Comment by chicks** [comment]
Heh, now I just need to figure out how to validate the gemspec :/

**Comment by davidsulc** [comment]
Yeah. It seems those files aren't being ignored properly. Maybe try using `gem.files.exclude` (https://github.com/technicalpickles/jeweler) ?

**Comment by cball** [comment]
I've got this fixed in #72.

**Comment by chicks** [comment]
Just cut a new gem.  Thanks!
