### ISSUE TITLE
on-demand support

### ISSUE THREAD

**Issue by sathappan** [chicks/sugarcrm#73]
Hi,

Thanks for this great gem. Totally saved my time. Just wanted to know if it works for all editions of Sugar CRM like Enterprise, Community and so on. I assume it supports both on-demand and on-premise variants.. Please let me know. Thanks.

**Comment by davidsulc** [comment]
Hi,

I've personally only used it with the community version, but it should work for all editions (including on-demand and on-premise). It simply wraps the API provided by SugarCRM, so it will work as long as the API is available.
