### ISSUE TITLE
Is there any way to restrict the fields that are returned as per the "select_fields Array Optional. A list of fields to include in the results" from the REST API documentation?

### ISSUE THREAD

**Issue by aew** [chicks/sugarcrm#86]

**Comment by aew** [comment]
Found it:

@accounts = SugarCRM::Account.all({
      :fields=>['id'  , 'nombre_contact_c', 'estado_c', 'date_modified'],
      :limit=>10,
      :order_by=>'date_modified DESC',
    })

**Comment by chicks** [comment]
There are my favorite kind of issues!  :)
