### ISSUE TITLE
Custom Fields in Query Seem Broken

### ISSUE THREAD

**Issue by frugardc** [chicks/sugarcrm#9]
Getting an "unknown column" MYSQL error when querying against a custom field.

SugarCRM::Opportunity.all({:conditions => {:synced_c => "false"}})
JSON::ParserError: 665: unexpected token at 'MySQL error 1054: Unknown column 'opportunities.synced_c' in 'where clause''

Of course, a custom field called "synced" would wind up in a opportunities_cstm table.

**Comment by chicks** [comment]
Thanks for the bug!  Can you confirm you are using 0.9.4 of the gem?  I just put in a fix for this...

**Comment by frugardc** [comment]
Was using 0.9.0.  Updated to 0.9.4.  Fixed now.  My bad not keeping up to date.  Little new at this.  Excellent work, and I'll keep posting bugs if I find.  Great gem.

**Comment by chicks** [comment]
Ahahaha, no worries.  Glad you like it - still very much a work in progress and people are just REALLY starting to use it. 

Let me know if you find any other issues, or if you would like to see a particular feature implemented!
