### ISSUE TITLE
"closed stream" error after migrated to Ruby 2 and Rails 4

### ISSUE THREAD

**Issue by AJAY2r** [chicks/sugarcrm#96]
Error => "IOError: closed stream"

Error detail :

/home/ajay/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/net/protocol.rb:211:in `write'
/home/ajay/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/net/protocol.rb:211:in`write0'
/home/ajay/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/net/protocol.rb:185:in `block in write'
/home/ajay/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/net/protocol.rb:202:in`writing'
/home/ajay/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/net/protocol.rb:184:in `write'
/home/ajay/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/net/http/generic_request.rb:325:in`write_header'
/home/ajay/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/net/http/generic_request.rb:136:in `exec'
/home/ajay/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/net/http.rb:1404:in`block in transport_request'
/home/ajay/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/net/http.rb:1403:in `catch'
/home/ajay/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/net/http.rb:1403:in`transport_request'
/home/ajay/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/net/http.rb:1376:in `request'
/home/ajay/.rvm/gems/ruby-2.0.0-p195/gems/fakeweb-1.3.0/lib/fake_web/ext/net_http.rb:50:in`request_with_fakeweb'
/home/ajay/.rvm/rubies/ruby-2.0.0-p195/lib/ruby/2.0.0/net/http.rb:1126:in `get'
/home/ajay/project/vubiqity/sugarcrm/lib/sugarcrm/connection/connection.rb:94:in`send!'
/home/ajay/project/vubiqity/sugarcrm/lib/sugarcrm/connection/api/get_module_fields.rb:12:in `get_module_fields'
/home/ajay/project/vubiqity/sugarcrm/lib/sugarcrm/module.rb:54:in`fields'
/home/ajay/project/vubiqity/sugarcrm/lib/sugarcrm/attributes/attribute_methods.rb:7:in `attributes_from_module'
/home/ajay/project/vubiqity/sugarcrm/lib/sugarcrm/finders/finder_methods.rb:226:in`block in all_attributes_exists?'
/home/ajay/project/vubiqity/sugarcrm/lib/sugarcrm/finders/finder_methods.rb:226:in `each'
/home/ajay/project/vubiqity/sugarcrm/lib/sugarcrm/finders/finder_methods.rb:226:in`all?'
/home/ajay/project/vubiqity/sugarcrm/lib/sugarcrm/finders/finder_methods.rb:226:in `all_attributes_exists?'
/home/ajay/project/vubiqity/sugarcrm/lib/sugarcrm/finders/finder_methods.rb:164:in`method_missing'
/home/ajay/project/vubiqity/rails4/eclipse_rails/app/models/providers/basic_information.rb:20:in `hit_base_query'

**Comment by chicks** [comment]
I'm skeptical of this inclusion in your stacktrace:

/home/ajay/.rvm/gems/ruby-2.0.0-p195/gems/fakeweb-1.3.0/lib/fake_web/ext/net_http.rb:50:in

Can you reproduce this error in stock ruby 2.0 outside of rails?

**Comment by AJAY2r** [comment]
It's because of fakeweb. Now it's working.
